site_name: Techniques de l'informatique du Cégep de Victoriaville
site_author: Étienne Rivard
theme:
  name: material
  custom_dir: overrides
  language: fr
  features:
    - content.code.copy
  logo: assets/logo32x32.png
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

plugins:
  - search
  - table-reader

extra_css:
  - css/extra.css

extra_javascript:
  - javascript/alltarget.js

nav:
  - 'Page principale': 'index.md'
  - 'Demander du tutorat': 'tutorat.md'
  - 'Équipe': 'equipe.md'
  - 'Stages':
      - 'Pour les élèves': 'stages-eleve.md'
      - 'Pour les employeurs': 'stages.md'
  - 'Intégrité académique':
      - "Citer l'intelligence artificielle": 'citer-ia.md'
      - 'Code emprunté': 'code-emprunte.md'
  - 'Références':
      - 'Abréviations': 'abreviations.md'
      - 'Traductions': 'traductions.md'
  - 'Guide Mac':
      - 'Page principale': 'guidemac/index.md'
      - 'Installation':
          - 'GIT': 'guidemac/git.md'
          - 'Java': 'guidemac/java.md'
          - 'Homebrew': 'guidemac/homebrew.md'
          - 'Kali Linux': 'guidemac/kali.md'
          - "Systèmes d'exploitation préinstallés": 'guidemac/os.md'
          - 'UTM': 'guidemac/utm.md'
          - 'UMLet': 'guidemac/umlet.md'
          - 'Windows XP': 'guidemac/xp.md'
      - 'Procédures':
          - 'Créer ISO': 'guidemac/creer-iso.md'
          - 'Convertir vmdk vers qcow2': 'guidemac/convertir-vmdk-vers-qcow2.md'
          - 'Convertir qcow2 vers vmdk': 'guidemac/convertir-qcow2-vers-vmdk.md'
  - 'Outils':
      - 'Développement': 'outils/developpement.md'
      - 'Intelligence artificielle': 'outils/ia.md'
      - 'Sécurité': 'outils/securite.md'
      - 'Données': 'outils/donnees.md'
      - 'Français': 'outils/francais.md'
      - 'Veille technologique': 'outils/veille.md'
      - 'Humour': 'outils/humour.md'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.escapeall:
      hardbreak: true # use \ to create new line
      nbsp: true # use \<space> to create &nbsp;
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

docs_dir: 'wiki'
site_dir: 'www'
use_directory_urls: True
